name: Deploy to VPS with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive project
        run: |
          tar --exclude='node_modules' --exclude='.bun' --ignore-failed-read -czf deploy.tar.gz .

      - name: Upload file via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "deploy.tar.gz"
          target: "/root"

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            TARGET_PATH="/root/ai-cashflow-forecaster"

            cd /root

            rm -rf $TARGET_PATH
            mkdir -p $TARGET_PATH

            tar -xzf deploy.tar.gz -C $TARGET_PATH
            rm deploy.tar.gz
            cd $TARGET_PATH

            systemctl enable docker --now
            chmod +x docker.sh

            JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
            KOLOSAL_API_KEY="${{ secrets.KOLOSAL_API_KEY }}" \
            KOLOSAL_BASE_URL="${{ secrets.KOLOSAL_BASE_URL }}" \

            docker-compose down -v
            ./docker.sh prod-restart
