name: Deploy to VPS with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files securely (without --delete)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if ! command -v rsync &> /dev/null; then
              sudo apt update
              sudo apt install -y rsync
            fi

            # Rsync dari runner ke server dengan mengabaikan node_modules, .git, dan .bun
            rsync -avz --exclude=node_modules --exclude=.git --exclude=.bun ./ /root/ai-cashflow-forecaster/

      - name: Run docker.sh on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/ai-cashflow-forecaster

            # export env biar docker.sh ga bengong
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            export KOLOSAL_API_KEY=${{ secrets.KOLOSAL_API_KEY }}
            export KOLOSAL_BASE_URL=${{ secrets.KOLOSAL_BASE_URL }}

            chmod +x docker.sh
            ./docker.sh up
